# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!


* 1) Create Numpy Array 
* 2) Built in Methods
    - 2.1) arange
    - 2.2) zeros, ones, eye
    - 2.3) linspace
    - 2.4) rand, randn, randint
    - 2.5) min, max, argmin, argmax
* 3) Reshaping

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

In [1]:
# !conda install numpy

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## 1) Creating NumPy Arrays

We can create an array by directly converting a list or list of lists:

In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 2) Built-in Methods

There are lots of built-in ways to generate Arrays

In [7]:
list(range(0, 11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [8]:
list(range(0, 11, 2))

[0, 2, 4, 6, 8, 10]

### 2.1) arange

In [9]:
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

### 2.2) zeros, ones and eye

Generate arrays of zeros or ones

### zeros

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### ones

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### eye

Creates an identity matrix

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 2.3)  linspace
Return evenly spaced numbers over a specified interval.

In [16]:
np.linspace(0, 100, 6)

array([  0.,  20.,  40.,  60.,  80., 100.])

In [17]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [18]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### 2.4) rand, randn, randint 

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1]``.

In [19]:
np.random.rand(3)

array([0.02731968, 0.8762578 , 0.75990563])

In [20]:
np.random.rand(5, 5)

array([[0.09575471, 0.82268812, 0.35296926, 0.89599057, 0.08579577],
       [0.26014641, 0.81917474, 0.55861582, 0.02185222, 0.46751549],
       [0.86134065, 0.43238172, 0.8769251 , 0.09078557, 0.09336153],
       [0.52089819, 0.12776237, 0.37046462, 0.68970213, 0.76236627],
       [0.47467491, 0.63185381, 0.91916529, 0.32320497, 0.92008942]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [21]:
np.random.randn(2)

array([ 0.65353722, -1.83959356])

In [22]:
np.random.randn(5, 5)

array([[ 0.5258353 ,  0.17843739,  0.87633656, -0.56771606, -1.68447783],
       [ 0.16772217,  0.38850787,  0.50201992, -1.28623179, -0.59286983],
       [ 0.42984141, -1.29616952, -1.22341275,  0.9997236 ,  2.51835769],
       [ 1.09918677, -0.37662337, -0.86170438,  0.29907716,  0.24816157],
       [-1.15631814, -1.31316441,  1.23617172, -2.45658258, -0.81284792]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [23]:
np.random.randint(1, 100)

8

In [24]:
np.random.randint(1, 100, 10)

array([40, 21, 24, 90, 35, 45, 28, 80, 49, 37])

In [25]:
np.random.randint(1, 100, (5, 5))

array([[35, 42, 82, 54, 57],
       [28, 24, 63,  9, 32],
       [58, 65, 91, 87, 58],
       [61, 37, 37, 66, 63],
       [65, 37, 95, 52, 16]])

### 2.5) max, min, argmax, argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [26]:
ranarr = np.random.randint(0,50,10)
ranarr

array([42,  9, 30, 22, 49,  6, 31,  9,  9, 34])

In [27]:
ranarr.max()

49

In [28]:
ranarr.argmax()

4

In [29]:
ranarr.min()

6

In [30]:
ranarr.argmin()

5

## 3) Reshape
Returns an array containing the same data with a new shape.

In [31]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)
linarr = np.linspace(0,2,11)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
arr.shape

(25,)

In [34]:
ranarr

array([39,  5, 40, 33, 40, 25, 12, 31, 24, 27])

In [35]:
ranarr.shape

(10,)

In [36]:
linarr

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [37]:
linarr.shape

(11,)

In [38]:
reshaped = arr.reshape(5, 5)
reshaped

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
reshaped.shape

(5, 5)

In [40]:
reshaped.reshape(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
reshaped.reshape(25).shape

(25,)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [44]:
arr.reshape(1, 25).shape

(1, 25)

In [45]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [46]:
arr.reshape(25, 1).shape

(25, 1)

: 

# Great Job!