# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.


* 1) Indexing
    - 1.1) Indexing 1D array (Vectors)
    - 1.2) Indexing 2D array (Matrices)
    - 1.3) Fancy Indexing
* 2) Selection

In [6]:
import numpy as np

In [7]:
#Creating sample array
arr = np.arange(30,40)

In [8]:
#Show
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

## 1) Indexing
The simplest way to pick one or some elements of an array looks very similar to python lists:

### 1.1) Indexing a 1D array (Vectors)

In [9]:
#Get a value at an index
arr[8]

38

In [10]:
#Get values in a range
arr[1:5]

array([31, 32, 33, 34])

In [11]:
#Get values in a range
arr[0:5]

array([30, 31, 32, 33, 34])

In [12]:
arr[:5]

array([30, 31, 32, 33, 34])

In [13]:
arr[3:]

array([33, 34, 35, 36, 37, 38, 39])

In [14]:
arr[3:7]

array([33, 34, 35, 36])

In [15]:
arr[3:7:2]

array([33, 35])

In [16]:
arr = np.arange(30,40)
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [17]:
#Setting a value with index range (Broadcasting)
arr[2:5] = 100

#Show
arr

array([ 30,  31, 100, 100, 100,  35,  36,  37,  38,  39])

### 1.2) Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [18]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [19]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [20]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [21]:
# Getting individual element value
arr_2d[1, 0]

20

In [22]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [24]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [25]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [26]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [27]:
arr_2d[::-1,::]

array([[35, 40, 45],
       [20, 25, 30],
       [ 5, 10, 15]])

In [28]:
arr_2d[:,::-1]

array([[15, 10,  5],
       [30, 25, 20],
       [45, 40, 35]])

In [29]:
arr_2d[::-1,::-1]

array([[45, 40, 35],
       [30, 25, 20],
       [15, 10,  5]])

### 1.3) Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [30]:
#Set up matrix
arr2d = np.random.randint(1, 100, (10,10))
arr2d

array([[17, 95, 56, 32, 69, 47, 67, 15, 10, 15],
       [76, 80, 95, 43,  3, 11, 89, 48, 33, 60],
       [69, 68, 27, 86, 72, 73, 23, 93, 80, 54],
       [47, 37, 90, 97, 31, 65, 41, 20, 87, 12],
       [ 8, 77,  1, 84, 11, 92, 36, 51, 57, 44],
       [66, 50, 73, 30, 95, 38, 82, 52, 23, 48],
       [47, 49, 15, 67, 25, 96, 92, 21, 70, 79],
       [87, 76,  1, 10, 13, 80, 39, 13, 98, 25],
       [81,  8, 54, 41, 27, 55, 41, 30, 90, 66],
       [42, 10, 37, 75, 36, 86, 33, 18, 71, 83]])

Fancy indexing allows the following

In [31]:
arr2d[[1,4,6,8]]

array([[76, 80, 95, 43,  3, 11, 89, 48, 33, 60],
       [ 8, 77,  1, 84, 11, 92, 36, 51, 57, 44],
       [47, 49, 15, 67, 25, 96, 92, 21, 70, 79],
       [81,  8, 54, 41, 27, 55, 41, 30, 90, 66]])

In [32]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[47, 49, 15, 67, 25, 96, 92, 21, 70, 79],
       [ 8, 77,  1, 84, 11, 92, 36, 51, 57, 44],
       [69, 68, 27, 86, 72, 73, 23, 93, 80, 54],
       [87, 76,  1, 10, 13, 80, 39, 13, 98, 25]])

In [33]:
arr2d[[1,4,6,8], 2:5]

array([[95, 43,  3],
       [ 1, 84, 11],
       [15, 67, 25],
       [54, 41, 27]])

## 2) Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [34]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True])

In [36]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True])

In [37]:
arr[bool_arr]

array([5, 6, 7, 8, 9])

In [38]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr[arr >= 5]

array([5, 6, 7, 8, 9])

In [40]:
x = 3
arr[arr > x]

array([4, 5, 6, 7, 8, 9])

In [41]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr[arr % 2 == 0]

array([2, 4, 6, 8])

: 

# Great Job!
